site_name: My Notes
site_url: "https://BilaroIman.github.io/my-notes/"

# Theme Configuration
theme:
  name: material
  palette:
    - scheme: slate  # Dark mode (Use 'default' for light mode)
      primary: blue
      accent: amber
  font:
    text: Montserrat
    code: Fira Code
  logo: assets/images/my-logo.png
  favicon: assets/images/my-favicon.ico
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand   # Auto-expand sections
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.tooltips   # Tooltip hover effects
    - content.code.annotate  # Code annotations
    - content.code.copy  # Copy button for code blocks

# Navigation Structure
nav:
  - CI/CD:
      - GitOps: CICD/index.md
      - GitHub Actions: CICD/GitHubActions.md
      - Jenkins: CICD/Jenkins.md
  - Kubernetes:
      - GitOps: Kubernetes/index.md
      - Helm: Kubernetes/Helm.md
      - Operators: Kubernetes/Operators.md
  - Terraform:
      - GitOps: Terraform/index.md
      - Modules: Terraform/Modules.md
      - State Management: Terraform/StateManagement.md
  - About: about.md

# Repository Information
repo_url: "https://github.com/BilaroIman/my-notes"
repo_name: "BilaroIman/my-notes"
edit_uri: "blob/main/docs/"

# Exclude directories from version control
exclude_dirs:
  - site

# Custom Styles & Scripts
extra_css:
  - assets/stylesheets/custom.css
extra_javascript:
  - assets/scripts/custom.js

# Plugins (Optional Enhancements)
plugins:
  - search
  - mkdocs-material-extensions  # Additional features for Material theme
  - macros  # Allows adding dynamic macros
  - git-revision-date-localized  # Shows last update date on pages
